_BASE_: "bdd_R_50_C4.yaml"
MODEL:
  PIXEL_MEAN: [71.1195, 74.6895, 74.001]
  PIXEL_STD:  [63.087, 67.6515, 70.4055]
  WEIGHTS: "See Instructions"
  RESNETS:
    STRIDE_IN_1X1: False
INPUT:
  MAX_SIZE_TRAIN: 1200
  FORMAT: "RGB"
